const data = [
  {
    name: "PHONES",
    products: [
      {
        name: "Samsung Galaxy S22",
        diagonal: 6.1,
        price: 29999,
        color: "Black",
        memory: "128GB/8GB",
        processor: "Android",
        img: 'sumsung1.jpg',
      },
      {
        name: "Apple iPhone 13",
        diagonal: 6.1,
        price: 35999,
        color: "Pink",
        memory: "128GB",
        processor: "iOS",
        img: 'apple1.jpg',
      },
      {
        name: "Motorola G32",
        diagonal: 6.5,
        price: 6999,
        color: "Rose Gold",
        memory: "128GB/6GB",
        processor: "Android",
        img: 'moto1.jpg',
      },
      {
        name: "Samsung Galaxy A53",
        diagonal: 6.5,
        price: 17777,
        color: "White",
        memory: "256GB/8GB",
        processor: "Samsung Exynos 1280",
        img: 'sumsung2.jpg',
      },
      {
        name: "Apple iPhone 11",
        diagonal: 6.1,
        price: 25499,
        color: "Black",
        memory: "128GB/4GB",
        processor: "iOS",
        img: 'apple1.jpg',
      },
      {
        name: "Motorola E40",
        diagonal: 6.5,
        price: 4999,
        color: "Gray",
        memory: "64GB/4GB",
        processor: "Android",
        img: 'moto2.jpg',
      },
      {
        name: "Nokia G11",
        diagonal: 6.5,
        price: 4799,
        color: "Chocolate",
        memory: "32GB/3GB",
        processor: "Android",
        img: 'nokia1.jpg',
      },
      {
        name: "Xiaomi Redmi Note 11",
        diagonal: 6.43,
        price: 8499,
        color: "Gray",
        memory: "128GB/4GB",
        processor: "Android",
        img: 'xiaomi1.jpg',
      },
      {
        name: "Apple iPhone 14 Pro",
        diagonal: 6.1,
        price: 83999,
        color: "Gold",
        memory: "1TB",
        processor: "iOS",
        img: 'apple3.jpg',
      },
    ],
  },
  {
    name: "LAPTOPS",
    products: [
      {
        name: "MackBook Air 2020",
        diagonal: 13.3,
        price: 42999,
        color: "Gray",
        processor: "Octa-core Apple M1",
        OS: "macOS Big Sur",
        memory: "256GB/8GB",
        img: 'mac1.jpg',
      },
      {
        name: "Aser Aspire 7",
        diagonal: 15.6,
        price: 36999,
        color: "Black",
        processor: "Six-core AMD Rizen 5",
        OS: "without OS",
        memory: "512GB/8GB",
      },
      {
        name: "Aser Aspire 5",
        diagonal: 15.6,
        price: 21999,
        color: "Silver",
        processor: "Quad Core AMD Rizen 3",
        OS: "without OS",
        memory: "512GB/8GB",
      },
      {
        name: "Asus Laptop",
        diagonal: 15.6,
        price: 20999,
        color: "Silver",
        processor: "Dual Core Intel Core i3",
        OS: "without OS",
        memory: "512GB/16GB",
      },
      {
        name: "Asus TUF Gaming",
        diagonal: 15.6,
        price: 37999,
        color: "Black",
        processor: "Six-core AMD Rizen 5",
        OS: "without OS",
        memory: "512GB/16GB",
      },
      {
        name: "Asus VivoBook",
        diagonal: 15.6,
        price: 23999,
        color: "Silver",
        processor: "Six-core AMD Rizen 5",
        OS: "without OS",
        memory: "512GB/12GB",
      },
      {
        name: "Lenovo IdeaPad Gaming 3",
        diagonal: 15.6,
        price: 29999,
        color: "Black",
        processor: "Quad Core Intel Core i5",
        OS: "without OS",
        memory: "256GB/8GB",
      },
      {
        name: "Lenovo V",
        diagonal: 14.0,
        price: 16999,
        color: "Black",
        processor: "Dual Core Intel Core i3",
        OS: "Windows 10 Pro",
        memory: "512GB/8GB",
      },
      {
        name: "MackBook Pro 2022",
        diagonal: 13.3,
        price: 54999,
        color: "Silver",
        processor: "Octa-core  Apple M2",
        OS: "macOS Montery",
        memory: "512GB/8GB",
        img: 'mac2.jpg',
      },
    ],
  },
  {
    name: "WATCHES",
    products: [
      {
        name: "Samsung Galaxy Watch",
        diagonal: 1.2,
        price: 10799,
        color: "Golden",
        memory: "16GB/1.5GB",
        processor: "Android Wear",
      },
      {
        name: "Samsung Galaxy Watch 5",
        diagonal: 1.4,
        price: 11999,
        color: "Silver",
        memory: "16GB/1.5GB",
        processor: "Android",
      },
      {
        name: "Amazfit GTR 4",
        diagonal: 1.43,
        price: 7499,
        color: "Brown",
        memory: "32GB/4GB",
        processor: "Another",
      },
      {
        name: "Xiaomi Watch S1",
        diagonal: 1.43,
        price: 5999,
        color: "Blue",
        memory: "16GB/1.5GB",
        processor: "Android",
      },
      {
        name: "Amazfit Bip 3",
        diagonal: 1.69,
        price: 1999,
        color: "Pink",
        memory: "16GB/1.7GB",
        processor: "Android",
      },
      {
        name: "Amazfit Bip 3 Pro",
        diagonal: 1.69,
        price: 2499,
        color: "Black",
        memory: "16GB/1.7GB",
        processor: "Android",
      },
      {
        name: "Aura X1 Pro",
        diagonal: 1.75,
        price: 1519,
        color: "White",
        memory: "8GB/1.0GB",
        processor: "Android",
      },
      {
        name: "Canyon Badian SW-68",
        diagonal: 1.28,
        price: 1799,
        color: "Black",
        memory: "8GB/1.0GB",
        processor: "Android",
      },
      {
        name: "Aura X2 Pro",
        diagonal: 1.75,
        price: 1575,
        color: "Red",
        memory: "16GB/1.6GB",
        processor: "Android",
      },
    ],
  },
];
