const data = [
  {
    name: "PHONES",
    products: [
      {
        name: "Samsung Galaxy S22",
        diagonal: 6.1,
        price: 29999,
        color: "Green",
        memory: "128GB/8GB",
        processor: "Android",
        main_images: 'images/phones/samsung1.jpg',
      },
      {
        name: "Apple iPhone 13",
        diagonal: 6.1,
        price: 35999,
        color: "Blue",
        memory: "128GB",
        processor: "iOS",
        main_images: 'images/phones/apple1.jpg',
      },
      {
        name: "Motorola G32",
        diagonal: 6.5,
        price: 6999,
        color: "Rose Gold",
        memory: "128GB/6GB",
        processor: "Android",
        main_images: 'images/phones/moto1.jpg',
      },
      {
        name: "Samsung Galaxy A53",
        diagonal: 6.5,
        price: 17777,
        color: "Light Blue",
        memory: "256GB/8GB",
        processor: "Samsung Exynos 1280",
        main_images: 'images/phones/samsung2.jpg',
      },
      {
        name: "Apple iPhone 11",
        diagonal: 6.1,
        price: 25499,
        color: "Yellow",
        memory: "128GB/4GB",
        processor: "iOS",
        main_images: 'images/phones/apple2.jpg',
      },
      {
        name: "Motorola E40",
        diagonal: 6.5,
        price: 4999,
        color: "Dlack",
        memory: "64GB/4GB",
        processor: "Android",
        main_images: 'images/phones/moto2.jpg',
      },
      {
        name: "Nokia G11",
        diagonal: 6.5,
        price: 4799,
        color: "Chocolate",
        memory: "32GB/3GB",
        processor: "Android",
        main_images: 'images/phones/nokia1.jpg',
      },
      {
        name: "Xiaomi Redmi Note 11",
        diagonal: 6.43,
        price: 8499,
        color: "Blue",
        memory: "128GB/4GB",
        processor: "Android",
        main_images: 'images/phones/xiaomi1.jpg',
      },
      {
        name: "Apple iPhone 14 Pro",
        diagonal: 6.1,
        price: 83999,
        color: "Purple",
        memory: "1TB",
        processor: "iOS",
        main_images: 'images/phones/apple3.jpg',
      },
    ],
  },
  {
    name: "LAPTOPS",
    products: [
      {
        name: "MacBook Air 2020",
        diagonal: 13.3,
        price: 42999,
        color: "Gray",
        processor: "Octa-core Apple M1",
        OS: "macOS Big Sur",
        memory: "256GB/8GB",
        main_images: 'images/laptops/mac1.jpg',
      },
      {
        name: "Acer Aspire 7",
        diagonal: 15.6,
        price: 36999,
        color: "Black",
        processor: "Six-core AMD Rizen 5",
        OS: "without OS",
        memory: "512GB/8GB",
        main_images:'images/laptops/aser1.jpg'
      },
      {
        name: "Acer Aspire 5",
        diagonal: 15.6,
        price: 21999,
        color: "Silver",
        processor: "Quad Core AMD Rizen 3",
        OS: "without OS",
        memory: "512GB/8GB",
        main_images:'images/laptops/aser2.jpg'
      },
      {
        name: "ASUS Laptop X515EA-BQ3231",
        diagonal: 15.6,
        price: 20999,
        color: "Silver",
        processor: "Dual Core Intel Core i3",
        OS: "without OS",
        memory: "512GB/16GB",
        main_images: 'images/laptops/asus1.jpg'
      },
      {
        name: "ASUS TUF Gaming F15",
        diagonal: 15.6,
        price: 37999,
        color: "Black",
        processor: "Six-core AMD Rizen 5",
        OS: "without OS",
        memory: "512GB/16GB",
        main_images:'images/laptops/asus2.jpg'
      },
      {
        name: "Asus Vivobook 15 M1502IA-BQ091",
        diagonal: 15.6,
        price: 28999,
        color: "Blue",
        processor: "8-core AMD Ryzen 7",
        OS: "without OS",
        memory: "512GB/12GB",
        main_images:'images/laptops/asus3.jpg'
      },
      {
        name: "Lenovo IdeaPad Gaming 3",
        diagonal: 15.6,
        price: 29999,
        color: "Black",
        processor: "Quad Core Intel Core i5",
        OS: "without OS",
        memory: "256GB/8GB",
        main_images:'images/laptops/lenovo1.jpg'
      },
      {
        name: "Lenovo IdeaPad 5 Pro 16ACH6",
        diagonal: 16.0,
        price: 48888,
        color: "Grey",
        processor: "AMD Ryzen 7 5800H ",
        OS: "Windows 10 Pro",
        memory: "512GB/16GB",
        main_images:'images/laptops/lenovo2.jpg'
      },
      {
        name: "Apple MacBook M1 Pro",
        diagonal: 16.2,
        price: 114999,
        color: "Silver",
        processor: "Apple M1 Pro",
        OS: "macOS Montery",
        memory: "512GB/16GB",
        main_images: 'images/laptops/mac2.jpg',
      },
    ],
  },
  {
    name: "WATCHES",
    products: [
      {
        name: "Samsung Galaxy Watch 4",
        diagonal: 1.2,
        price: 10799,
        color: "Golden",
        memory: "16GB/1.5GB",
        processor: "Android Wear",
        main_images: 'images/watches/samsungWatch1.1.jpg'
      },
      {
        name: "Samsung Galaxy Watch 5",
        diagonal: 1.4,
        price: 11999,
        color: "Silver",
        memory: "16GB/1.5GB",
        processor: "Android",
        main_images:'images/watches/samWa2.jpg'
      },
      {
        name: "Amazfit GTR 4",
        diagonal: 1.43,
        price: 7499,
        color: "Brown",
        memory: "32GB/4GB",
        processor: "Another",
        main_images:'images/watches/amazfitWatch1.jpg'
      },
      {
        name: "Xiaomi Watch S1",
        diagonal: 1.43,
        price: 5999,
        color: "Blue",
        memory: "16GB/1.5GB",
        processor: "Android",
        main_images:'images/watches/xiaomiWatch1.jpg'
      },
      {
        name: "Amazfit Bip 3",
        diagonal: 1.69,
        price: 1999,
        color: "Pink",
        memory: "16GB/1.7GB",
        processor: "Android",
        main_images: 'images/watches/amazfitW2.jpg'
      },
      {
        name: "Amazfit Bip 3 Pro",
        diagonal: 1.69,
        price: 2499,
        color: "Black",
        memory: "16GB/1.7GB",
        processor: "Android",
        main_images: 'images/watches/amazfitW3.jpg'
      },
      {
        name: "Aura X1 Pro",
        diagonal: 1.75,
        price: 1519,
        color: "White",
        memory: "8GB/1.0GB",
        processor: "Android",
        main_images: 'images/watches/auraW1.jpg'
      },
      {
        name: "Canyon Badian SW-68",
        diagonal: 1.28,
        price: 1799,
        color: "Black",
        memory: "8GB/1.0GB",
        processor: "Android",
        main_images: 'images/watches/amazfitW3.jpg'
      },
      {
        name: "Aura X2 Pro",
        diagonal: 1.75,
        price: 1575,
        color: "Red",
        memory: "16GB/1.6GB",
        processor: "Android",
        main_images: 'images/watches/auraW2.jpg'
      },
    ],
  },
];
