const salesData = [
	{
	  name: "PHONES",
	  products: [
		{
		  name: "Samsung Galaxy S21 FE",
		  diagonal: 6.4,
		  price: 23499,
		  color: "Purple",
		  memory: "128GB/6GB",
		  processor: "Android",
		  main_images: 'images/salesData/salePhone/samsung1.jpg',
		  image_arr: ['images/salesData/salePhone/samsung1.jpg', 'images/salesData/salePhone/samsung1.1.jpg', 'images/salesData/salePhone/samsung1.2.jpg'],
		},
		{
		  name: "Xiaomi 12T",
		  diagonal: 6.67,
		  price: 21999,
		  color: "Blue",
		  memory: "256GB/8GB",
		  processor: "Android",
		  main_images: 'images/salesData/salePhone/xiaomi1.jpg',
		  image_arr: ['images/salesData/salePhone/xiaomi1.jpg', 'images/salesData/salePhone/xiaomi1.1.jpg', 'images/salesData/salePhone/xiaomi1.2.jpg'],
		},
		{
		  name: "Apple iPhone SE",
		  diagonal: 4.7,
		  price: 21999,
		  color: "Golden",
		  memory: "64GB",
		  processor: "iOS",
		  main_images: 'images/salesData/salePhone/iphone1.jpg',
		  image_arr: ['images/salesData/salePhone/iphone1.jpg', 'images/salesData/salePhone/iphone1.1.jpg', 'images/salesData/salePhone/iphone1.2.jpg'],
		},
	]
	},
	{
	name: "LAPTOPS",
    products: [
      {
        name: "Apple MacBook Air M1",
        diagonal: 13.3,
        price: 39999,
        color: "Gold",
        processor: "Octa-core Apple M1",
        OS: "macOS Big Sur",
        memory: "256GB/8GB",
        main_images: 'images/salesData/saleLaptops/mac1.jpg',
        image_arr: ['images/salesData/saleLaptops/mac1.jpg', 'images/salesData/saleLaptops/mac1.1.jpg', 'images/salesData/saleLaptops/mac1.2.jpg'],
      },
      {
        name: "Acer Aspire 3",
        diagonal: 15.6,
        price: 23999,
        color: "Silver",
        processor: "Quad core Intel Core i5-1135G7",
        OS: "without OS",
        memory: "512GB/8GB",
        main_images:'images/salesData/saleLaptops/acer1.jpg',
        image_arr: ['images/salesData/saleLaptops/acer1.jpg', 'images/salesData/saleLaptops/acer1.1.jpg', 'images/salesData/saleLaptops/acer1.2.jpg'],
      },
      {
        name: "ASUS TUF Gaming A15",
        diagonal: 15.6,
        price: 37999,
        color: "Black",
        processor: "Six-core processor AMD Rizen 3",
        OS: "without OS",
        memory: "512GB/16GB",
        main_images:'images/salesData/saleLaptops/asus1.jpg',
        image_arr: ['images/salesData/saleLaptops/asus1.jpg', 'images/salesData/saleLaptops/asus1.1.jpg', 'images/salesData/saleLaptops/asus1.2.jpg'],
      },
	]
},
{
	name: "WATCHES",
    products: [
      {
        name: " Samsung Galaxy Watch 5 Pro",
        diagonal: 1.4,
        price: 17999,
        color: "Grey",
        memory: "16GB/1.5GB",
        processor: "Dual core Samsung Exynos W920",
        main_images: 'images/salesData/saleWatches/sumsungWatch1.jpg',
        image_arr:['images/salesData/saleWatches/sumsungWatch1.jpg','images/salesData/saleWatches/sumsungWatch1.1.jpg','images/salesData/saleWatches/sumsungWatch1.2.jpg'],
      },
      {
        name: "Samsung Galaxy Watch 4 Classic",
        diagonal: 1.4,
        price: 13599,
        color: "Black",
        memory: "16GB/1.5GB",
        processor: "Android Wear",
        main_images:'images/salesData/saleWatches/samsungW2.jpg',
        image_arr: ['images/salesData/saleWatches/samsungW2.jpg', 'images/salesData/saleWatches/samsungW2.1.jpg', 'images/salesData/saleWatches/samsungW2.2.jpg'],
      },
      {
        name: "Garmin Venu 2S",
        diagonal: 1.4,
        price: 18999,
        color: "Grey",
        memory: "32GB/4GB",
        processor: "Another",
        main_images:'images/salesData/saleWatches/garminW1.jpg',
        image_arr: ['images/salesData/saleWatches/garminW1.jpg', 'images/salesData/saleWatches/garminW1.1.jpg', 'images/salesData/saleWatches/garminW1.2.jpg'],
      },
	]
},
{
	name: "TABLETS",
    products:[
      {
        name: "Apple iPad",
        diagonal: 10.2,
        price: 25999,
        color: "Gray",
        processor: "A13 Bionic",
        OS: "iPadOS",
        memory: "64GB",
        main_images: 'images/salesData/saleTab/ip1.jpg',
        image_arr: ['images/salesData/saleTab/ip1.jpg', 'images/salesData/saleTab/ip1.1.jpg', 'images/salesData/saleTab/ip1.2.jpg'],
      },
      {
        name: "Lenovo Yoga Tab 11 LTE",
        diagonal: 11.0,
        price: 19999,
        color: "Gray",
        processor: "MediaTek Helio G90T",
        OS: "Android 11",
        memory: "256GB/8GB",
        main_images: 'images/salesData/saleTab/lenovoTab1.jpg',
        image_arr: ['images/salesData/saleTab/lenovoTab1.jpg', 'images/salesData/saleTab/lenovoTab1.1.jpg', 'images/salesData/saleTab/lenovoTab1.2.jpg'],
      },
      {
        name: "Samsung Galaxy Tab A8",
        diagonal: 10.5,
        price: 11499,
        color: "Gray",
        processor: "UNISOC Tiger T618",
        OS: "Android",
        memory: "64GB/4GB",
        main_images: 'images/salesData/saleTab/samTab1.jpg',
        image_arr: ['images/salesData/saleTab/samTab1.jpg', 'images/salesData/saleTab/samTab1.1.jpg', 'images/salesData/saleTab/samTab1.2.jpg'],
      },
	]
}
	]